<?php
spl_autoload_register(function($className) {
	$className = strtolower ($className);
	$classMap = array (
		'noresources\sql\statementexception' => 'Statements/Base.php',
		'noresources\sql\tablereference' => 'Statements/Base.php',
		'noresources\sql\statement' => 'Statements/Base.php',
		'noresources\sql\droptablequery' => 'Statements/DropTable.php',
		'noresources\sql\statementcontextparameter' => 'Statements/Context.php',
		'noresources\sql\statementcontextparametermap' => 'Statements/Context.php',
		'noresources\sql\statementcontext' => 'Statements/Context.php',
		'noresources\sql\resultcolumnreference' => 'Statements/Select.php',
		'noresources\sql\joinclause' => 'Statements/Select.php',
		'noresources\sql\selectquery' => 'Statements/Select.php',
		'noresources\sql\statementbuilder' => 'Statements/Builder.php',
		'noresources\sql\insertquery' => 'Statements/Insert.php',
		'noresources\sql\updatequery' => 'Statements/Update.php',
		'noresources\sql\createtablequery' => 'Statements/CreateTable.php',
		'noresources\sql\deletequery' => 'Statements/Delete.php',
		'noresources\sql\constants' => 'Constants.php',
		'noresources\sql\sqlite\constants' => 'DBMS/SQLite/Constants.php',
		'noresources\sql\sqlite\statementbuilder' => 'DBMS/SQLite/StatementBuilder.php',
		'noresources\sql\sqlite\connection' => 'DBMS/SQLite/Connection.php',
		'noresources\sql\sqlite\preparedstatement' => 'DBMS/SQLite/PreparedStatement.php',
		'noresources\sql\sqlite\recordset' => 'DBMS/SQLite/Recordset.php',
		'noresources\sql\reference\statementbuilder' => 'DBMS/Reference/Builder.php',
		'noresources\sql\reference\connection' => 'DBMS/Reference/Connection.php',
		'noresources\sql\reference\preparedstatement' => 'DBMS/Reference/PreparedStatement.php',
		'noresources\sql\connectionexception' => 'DBMS/Connection.php',
		'noresources\sql\connection' => 'DBMS/Connection.php',
		'noresources\sql\connectionhelper' => 'DBMS/Connection.php',
		'noresources\sql\parameterarray' => 'DBMS/PreparedStatement.php',
		'noresources\sql\preparedstatement' => 'DBMS/PreparedStatement.php',
		'noresources\sql\structureexception' => 'Structure/Structures.php',
		'noresources\sql\structureelement' => 'Structure/Structures.php',
		'noresources\sql\tablecolumnstructure' => 'Structure/Structures.php',
		'noresources\sql\tablestructure' => 'Structure/Structures.php',
		'noresources\sql\tablesetstructure' => 'Structure/Structures.php',
		'noresources\sql\datasourcestructure' => 'Structure/Structures.php',
		'noresources\sql\structureserializer' => 'Structure/Serializers.php',
		'noresources\sql\jsonstructureserializer' => 'Structure/Serializers.php',
		'noresources\sql\xmlstructureserializer' => 'Structure/Serializers.php',
		'noresources\sql\structureresolverexception' => 'Structure/Resolver.php',
		'noresources\sql\structureresolver' => 'Structure/Resolver.php',
		'noresources\sql\tableconstraint' => 'Structure/TableConstraints.php',
		'noresources\sql\columntableconstraint' => 'Structure/TableConstraints.php',
		'noresources\sql\primarykeytableconstraint' => 'Structure/TableConstraints.php',
		'noresources\sql\uniquetableconstraint' => 'Structure/TableConstraints.php',
		'noresources\sql\foreignkeytableconstraint' => 'Structure/TableConstraints.php',
		'noresources\sql\expression' => 'Expressions/Base.php',
		'noresources\sql\preformattedexpression' => 'Expressions/Base.php',
		'noresources\sql\keywordexpression' => 'Expressions/Base.php',
		'noresources\sql\literalexpression' => 'Expressions/Base.php',
		'noresources\sql\parameterexpression' => 'Expressions/Base.php',
		'noresources\sql\columnexpression' => 'Expressions/Base.php',
		'noresources\sql\tableexpression' => 'Expressions/Base.php',
		'noresources\sql\caseoptionexpression' => 'Expressions/Case.php',
		'noresources\sql\caseexpression' => 'Expressions/Case.php',
		'noresources\sql\functionexpression' => 'Expressions/Functions.php',
		'noresources\sql\expressionevaluationexception' => 'Expressions/Evaluator.php',
		'noresources\sql\evaluable' => 'Expressions/Evaluator.php',
		'noresources\sql\expressionevaluator' => 'Expressions/Evaluator.php',
		'noresources\sql\polishnotationoperation' => 'Expressions/Evaluator.php',
		'noresources\sql\binarypolishnotationoperation' => 'Expressions/Evaluator.php',
		'noresources\sql\unarypolishnotationoperation' => 'Expressions/Evaluator.php',
		'noresources\sql\listexpression' => 'Expressions/Chunks.php',
		'noresources\sql\parenthesisexpression' => 'Expressions/Chunks.php',
		'noresources\sql\unaryoperatorexpression' => 'Expressions/Chunks.php',
		'noresources\sql\binaryoperatorexpression' => 'Expressions/Chunks.php',
		'noresources\sql\inoperatorexpression' => 'Expressions/Chunks.php',
		'noresources\sql\betweenexpression' => 'Expressions/Chunks.php',
		'noresources\sql\recordset' => 'Recordset.php'
	); // classMap

	if (\array_key_exists ($className, $classMap)) {
		require_once(__DIR__ . '/' . $classMap[$className]);
	}
});