<?php
// NAmespace
namespace NoreSources\SQL\QueryResult;

/**
 * Interface for all results of a query that add rows in tables.
 */
interface InsertionQueryResult extends QueryResult
{

	/**
	 * Get the last sequence / autoincrement generated by the DBMS
	 *
	 * @return mixed
	 */
	function getInsertId();
}

