<?php
/**
 * Copyright © 2012 - 2020 by Renaud Guillard (dev@nore.fr)
 * Distributed under the terms of the MIT License, see LICENSE
 */
/**
 *
 * @package SQL
 */
namespace NoreSources\SQL\QueryResult;

/**
 * Interface for all results of a query that add rows in tables.
 */
interface InsertionQueryResult extends QueryResult
{

	/**
	 * Get the last sequence / autoincrement generated by the DBMS
	 *
	 * @return mixed
	 */
	function getInsertId();
}

